services:
  jtcpfwd:
    build:
      context: .  
      dockerfile: Dockerfile
    restart: unless-stopped
     # examples ports
    ports:
      - "1234:1234"
      - "1235:1235"
    # examples command
    command: 
      - "1234"
      - "172.16.32.101:80"
      - "1235"
      - "172.16.32.101:80"
